language: node_js
deploy:
  api_key:
    secure: HX2ifSSzDnMpmJQ5N6QsRViTeLboGdVu6Ywe+lwTOJvrzH2YzFRufb5Zi5chFDlaaCIQx3D8viS2WFBqmcje8Hd58F8bslT0OMn7gabWEONQ+NRNGK9j4M8xgAR/FKP3QJp0FA8mBcV4Vx8rz4RCLHISfGOw0FtPqRdGdeiDDzc=
  provider: npm
  email: john@mclear.co.uk
